// Copy the exact Three.js files this game imports into vendor/, so the page
// makes no external request.
//
// Why this exists: game portals (Poki, CrazyGames) reject a game that fetches
// anything from another origin - the game must keep working when unpkg is
// slow, blocked, or gone. Pinning a CDN version is not enough, because the
// request still leaves the page.
//
// Why a script rather than a one-off copy: the import graph is ten files, not
// the four this game names. Copying by hand means missing one and finding out
// in a portal review. Re-run this after changing the `three` dependency:
//
//     node scripts/vendor-three.mjs
//
// It walks the real import graph from the entry points, so the set it copies
// is whatever the code actually needs on the day it runs.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const THREE = path.join(ROOT, 'node_modules', 'three');
const VENDOR = path.join(ROOT, 'vendor');

// The addons script.js imports, as paths inside the three package.
const ENTRIES = [
  'examples/jsm/postprocessing/EffectComposer.js',
  'examples/jsm/postprocessing/RenderPass.js',
  'examples/jsm/postprocessing/UnrealBloomPass.js',
  'examples/jsm/postprocessing/OutputPass.js',
];

const IMPORT_RE = /from\s+['"]([^'"]+)['"]/g;

/** Every file reachable from ENTRIES by relative import, as package paths. */
function closure() {
  const seen = new Set();
  const queue = [...ENTRIES];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    seen.add(rel);
    const src = fs.readFileSync(path.join(THREE, rel), 'utf8');
    for (const m of src.matchAll(IMPORT_RE)) {
      const spec = m[1];
      // Bare specifiers ('three') stay bare - the import map resolves them.
      if (!spec.startsWith('.')) continue;
      queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), spec)));
    }
  }
  return [...seen].sort();
}

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  return fs.statSync(to).size;
}

fs.rmSync(VENDOR, { recursive: true, force: true });

let total = copy(
  path.join(THREE, 'build', 'three.module.min.js'),
  path.join(VENDOR, 'three.module.min.js'),
);
let count = 1;

for (const rel of closure()) {
  // examples/jsm/postprocessing/X.js -> vendor/jsm/postprocessing/X.js, so the
  // relative imports between addons keep resolving unchanged.
  const out = rel.replace(/^examples\//, '');
  total += copy(path.join(THREE, rel), path.join(VENDOR, out));
  count += 1;
}

const version = JSON.parse(
  fs.readFileSync(path.join(THREE, 'package.json'), 'utf8'),
).version;

fs.writeFileSync(
  path.join(VENDOR, 'README.md'),
  [
    '# vendor/',
    '',
    `Generated by \`node scripts/vendor-three.mjs\` from three@${version}.`,
    'Do not edit by hand - re-run the script instead.',
    '',
    'These files are here so the game makes no external request, which is a',
    'hard requirement for the web game portals. MIT licensed, same as three.',
    '',
  ].join('\n'),
);

console.log(`${count} files, ${(total / 1024).toFixed(0)} KB from three@${version}`);
